image: node:12.13.1

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - production

staging:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=client-bank-react-app --api-key=$HEROKU_API_KEY
  only:
    - master
