export const GET_ACCOUNTS_REQUEST = "GET_ACCOUNTS_REQUEST"
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS"
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE"

export const DEPOSIT_ACCOUNT_REQUEST = "DEPOSIT_ACCOUNT_REQUEST";
export const DEPOSIT_ACCOUNT_SUCCESS = "DEPOSIT_ACCOUNT_SUCCESS";
export const DEPOSIT_ACCOUNT_FAILURE = "DEPOSIT_ACCOUNT_FAILURE";


export const WITHDRAW_ACCOUNT_REQUEST = "WITHDRAW_ACCOUNT_REQUEST";
export const WITHDRAW_ACCOUNT_SUCCESS = "WITHDRAW_ACCOUNT_SUCCESS";
export const WITHDRAW_ACCOUNT_FAILURE = "WITHDRAW_ACCOUNT_FAILURE";


export const TRANSFER_ACCOUNT_REQUEST = "TRANSFER_ACCOUNT_REQUEST";
export const TRANSFER_ACCOUNT_SUCCESS = "TRANSFER_ACCOUNT_SUCCESS";
export const TRANSFER_ACCOUNT_FAILURE = "TRANSFER_ACCOUNT_FAILURE";
