export const GET_CUSTOMERS_REQUEST = "GET_CUSTOMERS_REQUEST"
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"
export const GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE"

export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST"
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const CREATE_CUSTOMER_FAILURE = "CREATE_CUSTOMER_FAILURE"

export const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST"
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS"
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE"

export const REMOVE_CUSTOMER_REQUEST = "REMOVE_CUSTOMER_REQUEST"
export const REMOVE_CUSTOMER_SUCCESS = "REMOVE_CUSTOMER_SUCCESS"
export const REMOVE_CUSTOMER_FAILURE = "REMOVE_CUSTOMER_FAILURE"

export const REMOVE_ACCOUNT_REQUEST = "REMOVE_ACCOUNT_REQUEST"
export const REMOVE_ACCOUNT_SUCCESS = "REMOVE_ACCOUNT_SUCCESS"
export const REMOVE_ACCOUNT_FAILURE = "REMOVE_ACCOUNT_FAILURE"
